/* Host table generator for the A0 and A3 searches.
 *
 *   ./gen_tables > tables.h
 *       factored quarter-turn transitions for the permutation and
 *       orientation ranks, and one pattern database for each projection
 *   ./gen_tables --perimeter R > perimeter.h
 *       every state within R moves of solved, sorted by rank, packed as
 *       [rank:22][move toward solved:4][distance:3]
 *
 * Reuses the upstream move, rank, and unrank helpers without editing them.
 */
#define main baseline_cli_main
#include "solver.c"
#undef main

#include <inttypes.h>

static uint16_t perm_turn[3][PERMUTATIONS], ori_turn[3][ORIENTATIONS];
static uint8_t perm_pdb[PERMUTATIONS], ori_pdb[ORIENTATIONS];

/* Same construction as the first half of build_table(): rank 0 of the other
 * coordinate is used as a carrier, which is valid because the permutation
 * and orientation evolve independently (report.md section 4).
 */
static void build_transitions(void)
{
    state_t state;
    for (uint16_t rank = 0; rank < PERMUTATIONS; ++rank) {
        unrank_state((uint32_t) rank * ORIENTATIONS, &state);
        for (uint8_t face = 0; face < 3; ++face) {
            state_t next = quarter_turn(state, face);
            perm_turn[face][rank] =
                (uint16_t) (rank_state(&next) / ORIENTATIONS);
        }
    }
    for (uint16_t rank = 0; rank < ORIENTATIONS; ++rank) {
        unrank_state(rank, &state);
        for (uint8_t face = 0; face < 3; ++face) {
            state_t next = quarter_turn(state, face);
            ori_turn[face][rank] =
                (uint16_t) (rank_state(&next) % ORIENTATIONS);
        }
    }
}

/* Breadth-first search over one projection. The abstract graph has an edge
 * wherever the full graph has one, so an abstract distance never exceeds the
 * distance of any state that projects onto it.
 */
static void build_pdb(const uint16_t *turn, uint16_t size, uint8_t *pdb)
{
    static uint16_t queue[PERMUTATIONS];
    uint16_t head = 0, tail = 1;
    memset(pdb, UINT8_MAX, size);
    pdb[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        uint16_t here = queue[head++];
        for (uint8_t face = 0; face < 3; ++face) {
            uint16_t there = here;
            for (uint8_t power = 0; power < 3; ++power) {
                there = turn[face * size + there];
                if (pdb[there] == UINT8_MAX) {
                    pdb[there] = (uint8_t) (pdb[here] + 1);
                    queue[tail++] = there;
                }
            }
        }
    }
    if (tail != size) {
        fprintf(stderr, "projection BFS reached %u of %u ranks\n", tail, size);
        exit(EXIT_FAILURE);
    }
}

/* Exact distance of every state, by BFS over the full graph. Used only on
 * the host, to select and audit the perimeter; never linked into a target.
 */
static uint8_t *full_distance(void)
{
    uint8_t *distance = malloc(STATES);
    uint32_t *queue = malloc((size_t) STATES * sizeof *queue);
    uint32_t head = 0, tail = 1;
    if (!distance || !queue) {
        fputs("allocation failed\n", stderr);
        exit(EXIT_FAILURE);
    }
    memset(distance, UINT8_MAX, STATES);
    distance[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        uint32_t here = queue[head++];
        for (uint8_t face = 0; face < 3; ++face) {
            uint16_t p = (uint16_t) (here / ORIENTATIONS);
            uint16_t o = (uint16_t) (here % ORIENTATIONS);
            for (uint8_t power = 0; power < 3; ++power) {
                p = perm_turn[face][p];
                o = ori_turn[face][o];
                uint32_t there = (uint32_t) p * ORIENTATIONS + o;
                if (distance[there] == UINT8_MAX) {
                    distance[there] = (uint8_t) (distance[here] + 1);
                    queue[tail++] = there;
                }
            }
        }
    }
    free(queue);
    return distance;
}

/* Packed perimeter entry for one state at distance d <= radius. The move is
 * the first, in move_names order, that leads one step closer to solved; the
 * solved state stores the sentinel 9, which is never a legal move.
 */
static uint32_t perimeter_entry(uint32_t rank, const uint8_t *distance)
{
    uint8_t d = distance[rank], move = 9;
    if (d) {
        for (move = 0; move < MOVES; ++move) {
            uint16_t p = (uint16_t) (rank / ORIENTATIONS);
            uint16_t o = (uint16_t) (rank % ORIENTATIONS);
            for (uint8_t q = 0; q <= move % 3U; ++q) {
                p = perm_turn[move / 3U][p];
                o = ori_turn[move / 3U][o];
            }
            if (distance[(uint32_t) p * ORIENTATIONS + o] == d - 1U)
                break;
        }
    }
    return rank << 7 | (uint32_t) move << 3 | d;
}

static void emit_perimeter(uint8_t radius)
{
    uint8_t *distance = full_distance();
    uint32_t count = 0;
    for (uint32_t rank = 0; rank < STATES; ++rank)
        count += distance[rank] <= radius;
    printf("/* Generated by gen_tables.c --perimeter %u; do not edit. */\n",
           radius);
    printf("#include <stdint.h>\n\n");
    printf("enum { PERIMETER_RADIUS = %u, PERIMETER_SIZE = %" PRIu32
           " };\n\n", radius, count);
    printf("/* [rank:22][move toward solved:4][distance:3], sorted by rank */\n");
    printf("static const uint32_t perimeter[%" PRIu32 "] = {", count);
    uint32_t i = 0;
    for (uint32_t rank = 0; rank < STATES; ++rank) {
        if (distance[rank] > radius)
            continue;
        printf("%s%s%" PRIu32, i ? "," : "", i % 8 ? "" : "\n    ",
               perimeter_entry(rank, distance));
        ++i;
    }
    printf("\n};\n");
    free(distance);
}

static void emit_u16(const char *name, const uint16_t *table, unsigned rows,
                     unsigned columns)
{
    printf("static const uint16_t %s[%u][%u] = {\n", name, rows, columns);
    for (unsigned row = 0; row < rows; ++row) {
        printf("    {");
        for (unsigned i = 0; i < columns; ++i)
            printf("%s%s%u", i ? "," : "", i % 16 ? "" : "\n     ",
                   table[row * columns + i]);
        printf("},\n");
    }
    printf("};\n\n");
}

static void emit_u8(const char *name, const uint8_t *table, unsigned size)
{
    printf("static const uint8_t %s[%u] = {", name, size);
    for (unsigned i = 0; i < size; ++i)
        printf("%s%s%u", i ? "," : "", i % 24 ? "" : "\n    ", table[i]);
    printf("\n};\n\n");
}

int main(int argc, char **argv)
{
    build_transitions();
    if (argc == 3 && !strcmp(argv[1], "--perimeter") && argv[2][0] >= '1' &&
        argv[2][0] <= '9' && !argv[2][1]) {
        emit_perimeter((uint8_t) (argv[2][0] - '0'));
        return output_failed();
    }
    if (argc != 1) {
        fprintf(stderr, "usage: %s [--perimeter RADIUS]\n", argv[0]);
        return 2;
    }
    build_pdb(&perm_turn[0][0], PERMUTATIONS, perm_pdb);
    build_pdb(&ori_turn[0][0], ORIENTATIONS, ori_pdb);

    printf("/* Generated by gen_tables.c; do not edit. */\n");
    printf("#include <stdint.h>\n\n");
    printf("enum { PERM_RANKS = %d, ORI_RANKS = %d };\n\n", PERMUTATIONS,
           ORIENTATIONS);
    emit_u16("perm_turn", &perm_turn[0][0], 3, PERMUTATIONS);
    emit_u16("ori_turn", &ori_turn[0][0], 3, ORIENTATIONS);
    emit_u8("perm_pdb", perm_pdb, PERMUTATIONS);
    emit_u8("ori_pdb", ori_pdb, ORIENTATIONS);
    return output_failed();
}
