/* Host table generator for the A0 search.
 * Emits tables.h: factored quarter-turn transitions for the permutation and
 * orientation ranks, and one pattern database for each projection.
 *
 *   make tables.h
 *
 * Reuses the upstream move, rank, and unrank helpers without editing them.
 */
#define main baseline_cli_main
#include "solver.c"
#undef main

static uint16_t perm_turn[3][PERMUTATIONS], ori_turn[3][ORIENTATIONS];
static uint8_t perm_pdb[PERMUTATIONS], ori_pdb[ORIENTATIONS];

/* Same construction as the first half of build_table(): rank 0 of the other
 * coordinate is used as a carrier, which is valid because the permutation
 * and orientation evolve independently (report.md section 4).
 */
static void build_transitions(void)
{
    state_t state;
    for (uint16_t rank = 0; rank < PERMUTATIONS; ++rank) {
        unrank_state((uint32_t) rank * ORIENTATIONS, &state);
        for (uint8_t face = 0; face < 3; ++face) {
            state_t next = quarter_turn(state, face);
            perm_turn[face][rank] =
                (uint16_t) (rank_state(&next) / ORIENTATIONS);
        }
    }
    for (uint16_t rank = 0; rank < ORIENTATIONS; ++rank) {
        unrank_state(rank, &state);
        for (uint8_t face = 0; face < 3; ++face) {
            state_t next = quarter_turn(state, face);
            ori_turn[face][rank] =
                (uint16_t) (rank_state(&next) % ORIENTATIONS);
        }
    }
}

/* Breadth-first search over one projection. The abstract graph has an edge
 * wherever the full graph has one, so an abstract distance never exceeds the
 * distance of any state that projects onto it.
 */
static void build_pdb(const uint16_t *turn, uint16_t size, uint8_t *pdb)
{
    static uint16_t queue[PERMUTATIONS];
    uint16_t head = 0, tail = 1;
    memset(pdb, UINT8_MAX, size);
    pdb[0] = 0;
    queue[0] = 0;
    while (head < tail) {
        uint16_t here = queue[head++];
        for (uint8_t face = 0; face < 3; ++face) {
            uint16_t there = here;
            for (uint8_t power = 0; power < 3; ++power) {
                there = turn[face * size + there];
                if (pdb[there] == UINT8_MAX) {
                    pdb[there] = (uint8_t) (pdb[here] + 1);
                    queue[tail++] = there;
                }
            }
        }
    }
    if (tail != size) {
        fprintf(stderr, "projection BFS reached %u of %u ranks\n", tail, size);
        exit(EXIT_FAILURE);
    }
}

static void emit_u16(const char *name, const uint16_t *table, unsigned rows,
                     unsigned columns)
{
    printf("static const uint16_t %s[%u][%u] = {\n", name, rows, columns);
    for (unsigned row = 0; row < rows; ++row) {
        printf("    {");
        for (unsigned i = 0; i < columns; ++i)
            printf("%s%s%u", i ? "," : "", i % 16 ? "" : "\n     ",
                   table[row * columns + i]);
        printf("},\n");
    }
    printf("};\n\n");
}

static void emit_u8(const char *name, const uint8_t *table, unsigned size)
{
    printf("static const uint8_t %s[%u] = {", name, size);
    for (unsigned i = 0; i < size; ++i)
        printf("%s%s%u", i ? "," : "", i % 24 ? "" : "\n    ", table[i]);
    printf("\n};\n\n");
}

int main(void)
{
    build_transitions();
    build_pdb(&perm_turn[0][0], PERMUTATIONS, perm_pdb);
    build_pdb(&ori_turn[0][0], ORIENTATIONS, ori_pdb);

    printf("/* Generated by gen_tables.c; do not edit. */\n");
    printf("#include <stdint.h>\n\n");
    printf("enum { PERM_RANKS = %d, ORI_RANKS = %d };\n\n", PERMUTATIONS,
           ORIENTATIONS);
    emit_u16("perm_turn", &perm_turn[0][0], 3, PERMUTATIONS);
    emit_u16("ori_turn", &ori_turn[0][0], 3, ORIENTATIONS);
    emit_u8("perm_pdb", perm_pdb, PERMUTATIONS);
    emit_u8("ori_pdb", ori_pdb, ORIENTATIONS);
    return output_failed();
}
