/* A0 search core: IDA* over (permutation rank, orientation rank).
 *
 * Shared verbatim by the host driver (ida.c) and the RV32I build
 * (rv32/main.c), so the code that passes the host gates is the code that
 * runs on the target. Include tables.h first.
 *
 * h(p, o) = max(perm_pdb[p], ori_pdb[o]). Each table is an exact distance in
 * a projection of the state graph, so neither overestimates, and the max of
 * two lower bounds is a lower bound. h is 0 only when both coordinates are
 * solved, which is exactly the solved state, so h == 0 doubles as the goal
 * test.
 *
 * No recursion and no heap: one bounded depth-first pass keeps its path in
 * fixed arrays indexed by depth, at most MAX_DEPTH deep.
 */
#ifndef IDA_H
#define IDA_H

#include <stdint.h>

enum { MAX_DEPTH = 11, NOT_FOUND = 0xFF };

typedef struct {
    uint32_t expanded;  /* nodes whose children were generated, incl. roots */
    uint32_t generated; /* children produced, one heuristic lookup each */
} ida_stats_t;

static inline uint8_t ida_h(uint16_t p, uint16_t o)
{
    uint8_t a = perm_pdb[p], b = ori_pdb[o];
    return a > b ? a : b;
}

/* One depth-first pass with cost bound `bound`. Moves are numbered
 * face * 3 + (quarter turns - 1), the upstream move_names order.
 * Returns the path length, or NOT_FOUND if no path fits the bound.
 */
static uint8_t ida_pass(uint16_t p0, uint16_t o0, uint8_t bound,
                        uint8_t *moves, ida_stats_t *stats)
{
    /* Frame d holds the node at depth d (node_p, node_o), the face being
     * tried from it and how many quarter turns of that face have been
     * applied so far (turns), and the most recent child (child_p, child_o).
     * R, R2, R' are generated by turning the previous sibling once more.
     */
    uint16_t node_p[MAX_DEPTH + 1], node_o[MAX_DEPTH + 1];
    uint16_t child_p[MAX_DEPTH + 1], child_o[MAX_DEPTH + 1];
    uint8_t face[MAX_DEPTH + 1], turns[MAX_DEPTH + 1];
    unsigned depth = 0;

    node_p[0] = child_p[0] = p0;
    node_o[0] = child_o[0] = o0;
    face[0] = 0;
    turns[0] = 0;
    ++stats->expanded;
    for (;;) {
        if (face[depth] == 3) { /* every child of this node tried */
            if (depth == 0)
                return NOT_FOUND;
            --depth;
            goto next_child;
        }
        /* A face never follows itself: R R2 is R', R R' is nothing. */
        if (depth > 0 && face[depth] == face[depth - 1]) {
            ++face[depth];
            continue;
        }
        {
            uint8_t f = face[depth];
            uint16_t p = perm_turn[f][child_p[depth]];
            uint16_t o = ori_turn[f][child_o[depth]];
            child_p[depth] = p;
            child_o[depth] = o;
            ++stats->generated;
            uint8_t h = ida_h(p, o);
            if (depth + 1U + h <= bound) {
                moves[depth] = (uint8_t) (f * 3U + turns[depth]);
                if (h == 0)
                    return (uint8_t) (depth + 1U);
                ++depth;
                ++stats->expanded;
                node_p[depth] = child_p[depth] = p;
                node_o[depth] = child_o[depth] = o;
                face[depth] = 0;
                turns[depth] = 0;
                continue;
            }
        }
    next_child:
        if (++turns[depth] == 3) { /* this face done: restart from node */
            turns[depth] = 0;
            ++face[depth];
            child_p[depth] = node_p[depth];
            child_o[depth] = node_o[depth];
        }
    }
}

/* Iterative deepening from bound h(root). Every path shorter than the
 * current bound was refuted by an earlier pass, so the first path found is
 * a shortest one. Returns its length (0 for the solved state), or NOT_FOUND
 * if nothing fits MAX_DEPTH, which no valid state does.
 */
static uint8_t ida_solve(uint16_t p, uint16_t o, uint8_t *moves,
                         ida_stats_t *stats)
{
    uint8_t bound = ida_h(p, o);
    if (bound == 0)
        return 0;
    for (; bound <= MAX_DEPTH; ++bound) {
        uint8_t length = ida_pass(p, o, bound, moves, stats);
        if (length != NOT_FOUND)
            return length;
    }
    return NOT_FOUND;
}

#endif
